import type { Metadata } from "next";
import Link from "next/link";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Button from "@/components/ui/Button";
import { site } from "@/data/site";
import { ArrowLeft, ArrowUpRight, Download, FileText } from "@/components/ui/Icons";

export const metadata: Metadata = {
  title: "Resume",
  description: `Resume of ${site.fullName} — ${site.role}, ${site.location}. View in the browser or download the PDF.`,
};

const pdf = site.resumeFile;

export default function ResumePage() {
  return (
    <>
      <Navbar />
      <main id="main" className="flex-1 pt-[calc(var(--nav-h)+32px)] pb-16 md:pt-[calc(var(--nav-h)+48px)]">
        <div className="container-site">
          <Link href="/" className="inline-flex items-center gap-2 font-mono text-xs text-fg-muted transition-colors hover:text-fg">
            <ArrowLeft size={14} /> Back to portfolio
          </Link>

          <div className="mt-6 grid gap-8 lg:grid-cols-12 lg:gap-12">
            {/* Side panel */}
            <aside className="lg:col-span-4">
              <div className="lg:sticky lg:top-24">
                <div className="flex items-center gap-3">
                  <span className="label-mono">resume</span>
                  <FileText size={14} className="text-fg-dim" />
                </div>
                <h1 className="mt-3 text-3xl font-semibold tracking-tightest text-fg md:text-4xl">{site.displayName}</h1>
                <p className="mt-1 font-mono text-sm text-accent">{site.role}</p>
                <p className="mt-4 max-w-sm text-[15px] leading-relaxed text-fg-muted">
                  The PDF below is the exact CV on file. It is not regenerated by this site.
                </p>

                <div className="mt-6 flex flex-col gap-2.5 sm:flex-row lg:flex-col">
                  <Button href={pdf} download={site.resumeDownloadName} className="w-full sm:w-auto lg:w-full">
                    <Download size={16} /> Download PDF
                  </Button>
                  <Button href={pdf} variant="secondary" external className="w-full sm:w-auto lg:w-full">
                    <ArrowUpRight size={16} /> Open PDF
                  </Button>
                  <Button href="/" variant="ghost" className="w-full sm:w-auto lg:w-full">
                    Back to portfolio
                  </Button>
                </div>

                <dl className="mt-8 grid grid-cols-2 gap-px overflow-hidden rounded-lg border border-line bg-line font-mono text-[11px] lg:grid-cols-1">
                  <div className="bg-bg-1 p-3">
                    <dt className="text-fg-dim">file</dt>
                    <dd className="mt-0.5 truncate text-fg">{site.resumeDownloadName}</dd>
                  </div>
                  <div className="bg-bg-1 p-3">
                    <dt className="text-fg-dim">location</dt>
                    <dd className="mt-0.5 text-fg">{site.location}</dd>
                  </div>
                  <div className="bg-bg-1 p-3">
                    <dt className="text-fg-dim">email</dt>
                    <dd className="mt-0.5 truncate text-fg">
                      <a href={`mailto:${site.email}`} className="hover:underline">
                        {site.email}
                      </a>
                    </dd>
                  </div>
                  <div className="bg-bg-1 p-3">
                    <dt className="text-fg-dim">status</dt>
                    <dd className="mt-0.5 text-fg">
                      <span className="mr-1.5 inline-block h-1.5 w-1.5 rounded-full bg-ok align-middle" aria-hidden />
                      {site.status}
                    </dd>
                  </div>
                </dl>
              </div>
            </aside>

            {/* Preview */}
            <div className="lg:col-span-8">
              <div className="overflow-hidden rounded-xl border border-line bg-bg-1">
                <div className="flex items-center justify-between border-b border-line bg-bg-2/60 px-4 py-2 font-mono text-[11px]">
                  <span className="text-fg-muted">preview · {site.resumeDownloadName}</span>
                  <a href={pdf} target="_blank" rel="noopener noreferrer" className="text-fg-dim hover:text-fg">
                    open in a new tab ↗
                  </a>
                </div>
                <object
                  data={`${pdf}#view=FitH&toolbar=0&navpanes=0`}
                  type="application/pdf"
                  className="block h-[70vh] w-full bg-[#1a1a1f] md:h-[82vh]"
                  aria-label={`PDF preview of ${site.displayName} resume`}
                >
                  {/* Fallback when the browser cannot embed PDFs (common on mobile). */}
                  <div className="flex h-full flex-col items-center justify-center gap-4 p-8 text-center">
                    <FileText size={28} className="text-fg-dim" />
                    <p className="max-w-xs text-sm leading-relaxed text-fg-muted">
                      This browser does not embed PDFs inline. Open it in a new tab or download it.
                    </p>
                    <div className="flex flex-wrap justify-center gap-2">
                      <Button href={pdf} size="sm" external>
                        Open PDF
                      </Button>
                      <Button href={pdf} size="sm" variant="secondary" download={site.resumeDownloadName}>
                        Download
                      </Button>
                    </div>
                  </div>
                </object>
              </div>
              <p className="mt-3 font-mono text-[11px] text-fg-dim md:hidden">
                On phones the inline preview may show only the first page — use Open PDF for the native viewer.
              </p>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
